// Shared data for /StudentProfiles/ and /StudentProfiles/Profile/
// Every entry is a real, publicly reported case from within the last 5 years. Sources are linked in the UI.
const PROFILES = [
  {
    id:'adirika', name:'Ashley Adirika', region:'global', tags:['admitted'], year:'2022', country:'United States',
    initials:'AA',
    stats:{},
    accepted:['Brown','Columbia','Cornell','Dartmouth','Harvard','Princeton','Yale','UPenn','Stanford','Vanderbilt','Emory'],
    waitlisted:[], rejected:[],
    highlight:'First-gen Nigerian-American admitted to all 8 Ivies plus Stanford — ~$4M in scholarships',
    extracurriculars:['Student Government Association president, Miami Beach Senior High School','Speech and debate team (recruited in 8th grade; went on to captain-level standing)','Founded "Our Story, Our Worth," a mentorship nonprofit for young women of color','Made a two-hour daily commute from Miami Gardens to attend Miami Beach Senior High'],
    essay:'Built her application narrative around her debate experience and her nonprofit work empowering young women of marginalized identities, tying both to her goal of using policy to reduce economic disparities.',
    story:'A first-generation Nigerian-American and debate champion from Miami, Adirika applied to all eight Ivy League schools on a whim and was accepted to every one, along with Stanford, Vanderbilt, and Emory — roughly $4 million in combined scholarship offers. She enrolled at Harvard on a full scholarship to study government.',
    sourceName:'CNN / ABC News, via ABC17News', sourceUrl:'https://abc17news.com/news/national-world/cnn-national/2022/06/12/a-florida-teen-was-accepted-into-all-eight-ivy-league-schools-and-seven-other-universities/'
  },
  {
    id:'ositade', name:'Femi Ositade', region:'global', tags:['admitted'], year:'2023', country:'Nigeria',
    initials:'FO',
    stats:{gpa:'4.04/4.0',sat:'800 Math / 760 EBRW'},
    accepted:['Harvard','Brown','Duke','Wesleyan','Carnegie Mellon (Qatar)','University of Miami','Howard','Stetson','Fisk','University of Toronto (multiple offers)'],
    waitlisted:[], rejected:[],
    highlight:'Perfect Math SAT — 14 scholarship offers worth $3.5M+, including Harvard',
    extracurriculars:['8 A1s and one B2 on the WASSCE (West African school-leaving exam)','Scored 358 on Nigeria\'s UTME — ranked 2nd nationally in 2023','Represented his school in national and international academic competitions','Active in his school\'s British/Nigerian dual-curriculum honors track'],
    essay:'Framed his application around a stated passion for quantum computing and mathematics, tying his olympiad and competition record to his intended major in Computational Physics.',
    story:'A Nigerian student at The Ambassadors College in Ota, Ositade scored a perfect 800 on the SAT Math section and 760 on Reading and Writing, with a 4.04 GPA. He received 14 scholarship offers worth more than $3.5 million combined, nine of them full-ride, including one from Harvard.',
    sourceName:'Vanguard News (Nigeria)', sourceUrl:'https://www.vanguardngr.com/2024/04/nigerian-teenager-femi-ositade-bags-scholarships-from-harvard-13-foreign-universities/'
  },
  {
    id:'hoang', name:'Hoàng Việt Giáng Hương', region:'global', tags:['admitted'], year:'2023', country:'Vietnam',
    initials:'HH',
    stats:{sat:'1560'},
    accepted:['Wesleyan University ($364,000 Freeman Scholarship, full ride)'],
    waitlisted:[], rejected:[],
    highlight:'Vietnamese student — full ride to Wesleyan on a 1560 SAT and an anti-racism advocacy essay',
    extracurriculars:['Scored 44/45 on her IB exams and 160/160 on the Duolingo English Test','Founded/chaired "Education for Vietnamese Youth," a group working to close education-access gaps in Vietnam','Partnered with Harvard-affiliated LabXChange to translate STEM materials into Vietnamese','Studied in Singapore on a government-funded ASEAN scholarship'],
    essay:'Wrote her application essay about her advocacy against racial discrimination during the COVID-19 pandemic, drawing on her experience as an international student navigating identity abroad.',
    story:'A Vietnamese student who studied in Singapore on an ASEAN scholarship, Hương scored 1560 on the SAT and 44/45 on her IB exams. She was awarded Wesleyan University\'s Freeman Scholarship, a full ride worth $364,000, after an application built around her advocacy work challenging racial discrimination during the COVID-19 pandemic.',
    sourceName:'Đại biểu Nhân dân (Vietnam)', sourceUrl:'https://daibieunhandan.vn/nu-sinh-dat-1560-1600-diem-sat-chinh-phuc-thanh-cong-hoc-bong-8-5-ty-dong-10311182.html'
  },
  {
    id:'sobirov', name:'Abdulaziz Sobirov', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'AS',
    stats:{gpa:'A*A*A (CAIE A-level: Math, Chemistry, Physics)',sat:'1560',ielts:'8.5'},
    accepted:['Harvard (~$360,000 scholarship, reported as $354,000–$366,000)','Grinnell College ($300,000 scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Harvard, near-full scholarship — from Khiva, Uzbekistan',
    extracurriculars:['Member of "Et Cetera," champion team of Zakovat Students\' League 2022–2023 (a national quiz bowl)','1st place regionally and 2nd nationally in the PIIMA Zakovat stage','Co-founder of the "PSAD" club and vice-president of "United Students" at Presidential School Tashkent','Interned at an international engineering company and worked with a PhD robotics professor','Competed in multiple regional, national and international science and math olympiads'],
    essay:'His Harvard admissions reader wrote back that his application stood out for its intellectual drive, love of robotics and engineering, and a track record of building projects aimed at helping people in need.',
    story:'A Presidential School Tashkent senior originally from Khiva, Sobirov captained a national quiz-bowl (Zakovat) champion team and built engineering and robotics projects. He intended to study Mechanical Engineering; at Harvard he has since majored in Mathematics and Statistics.',
    sourceName:'Gazeta.uz', sourceUrl:'https://gazeta.uz/en/2024/06/23/us-universities'
  },
  {
    id:'olloyorova', name:'Munira Olloyorova', region:'uz', tags:['admitted'], year:'2026', country:'Uzbekistan',
    initials:'MO',
    stats:{}, statsNote:'Specific GPA/SAT/ACT/IELTS scores were not published for this case — see the source for full context.',
    accepted:['University of Pennsylvania ($348,000 full-ride grant)'],
    waitlisted:[], rejected:[],
    highlight:'UPenn, full 4-year scholarship',
    extracurriculars:['Student at WIUT Academic Lyceum in Tashkent (group 2RUG1)'],
    essay:'Not publicly detailed in available coverage.',
    story:'A student at WIUT Academic Lyceum in Tashkent, Olloyorova was admitted to UPenn\'s College of Arts and Sciences (Class of 2030) with a grant covering all four years of tuition and living costs.',
    sourceName:'WIUT Academic Lyceum', sourceUrl:'https://lyceum.wiut.uz/en/news/1128-348k-to-liq-grant-sohibasi-olloyorova-munira-3'
  },
  {
    id:'baxshilloyev', name:'Amirbek Baxshilloyev', region:'uz', tags:['admitted'], year:'2026', country:'Uzbekistan',
    initials:'AB',
    stats:{sat:'1520',ielts:'8.5'},
    accepted:['Stanford','Caltech','Brown (combined $1.2M in scholarship offers)'],
    waitlisted:[], rejected:[],
    highlight:'Stanford, Caltech and Brown — from a regular public school in Bukhara, at age 16',
    extracurriculars:['Attended an ordinary secondary school rather than an elite specialized lyceum','Mentored through the Freshman Academy program'],
    essay:'Not publicly detailed in available coverage, beyond his stated focus on nuclear engineering.',
    story:'Baxshilloyev, from Bukhara, studied at an ordinary secondary school rather than an elite lyceum. With mentoring from the Freshman Academy program, he was admitted at age 16 to study nuclear engineering at three of the world\'s most selective universities.',
    sourceName:'Gov.uz (Youth Affairs Agency) / Talimxabarlari.uz', sourceUrl:'https://gov.uz/en/yoshlar/news/view/147132'
  },
  {
    id:'younger', name:'Kaitlyn Younger', region:'global', tags:['rejected'], year:'2022', country:'United States',
    initials:'KY',
    stats:{gpa:'3.95 unweighted / 4.65 weighted',sat:'1550'},
    accepted:[], waitlisted:[], rejected:['Stanford','Harvard','Yale','Brown','Cornell','UPenn','USC','UC Berkeley','Northwestern'],
    highlight:'1550 SAT, 3.95 GPA, 11 APs — rejected by 9 top schools',
    extracurriculars:['Founded her school\'s accounting club at McKinney High School (near Dallas, TX)','Performed in and directed roughly 30 school plays','Sang in the school choir; held a part-time job through high school','Took 11 AP classes'],
    essay:'Her guidance counselor described her personal statement and record as "extraordinary"; admissions consultants interviewed afterward suggested her extracurriculars, while genuine, weren\'t the kind of singular, high-profile achievement top schools prioritize.',
    story:'A Texas student with 11 AP classes, Younger was rejected from every reach school on her list despite academic credentials her teachers considered more than competitive. Her results, first profiled by The Wall Street Journal, became a widely cited example of how strong stats alone no longer guarantee admission at the most selective schools. She enrolled at Arizona State University\'s Barrett Honors College to study finance.',
    sourceName:'The Wall Street Journal, via NextGen Admit and ASU News', sourceUrl:'https://nextgenadmit.com/college-admissions-explained-why-top-students-get-rejected-from-every-ivy-league/'
  },
  {
    id:'nicholas', name:'"Nicholas" (case study, name changed)', region:'global', tags:['rejected'], year:'2022', country:'United States',
    initials:'N',
    stats:{gpa:'4.2',act:'36 (perfect)'},
    accepted:[], waitlisted:[], rejected:['Nearly every top-15 school he applied to'],
    highlight:'Perfect ACT and school-wide leadership — nearly every reach school said no',
    extracurriculars:['Salutatorian at a top New York City private school','Editor of the school newspaper','Student body president','Founded three separate clubs'],
    essay:'Not disclosed — this is an anonymized case study published by an admissions consultancy, with the student\'s name changed for privacy.',
    story:'A salutatorian at a top New York City private school, Nicholas edited the school newspaper, served as student body president, and founded three clubs. Confident in his profile, he applied almost exclusively to top-15 schools with a single safety school — and was rejected from nearly all of his reach schools, illustrating how stats and titles alone don\'t guarantee outcomes at the most selective level.',
    sourceName:'Command Education (admissions consultancy case study)', sourceUrl:'https://www.commandeducation.com/why-the-ivy-league-rejected-your-schools-valedictorian/'
  },
  {
    id:'zhong', name:'Stanley Zhong', region:'global', tags:['rejected'], year:'2023', country:'United States',
    initials:'SZ',
    stats:{gpa:'3.97 (4.42 weighted)',sat:'1590'},
    accepted:['University of Texas at Austin','3 other schools (4 of 18 total; not all publicly named)'],
    waitlisted:[],
    rejected:['MIT','Caltech','Carnegie Mellon','Stanford','Cornell','UC Berkeley','UCLA','UC San Diego','UC Santa Barbara','UC Davis','University of Michigan','University of Washington','and more (reports vary between 14 and 16 of 18 total)'],
    highlight:'Rejected by most of the 18 colleges he applied to — hired by Google instead',
    extracurriculars:['Founded RabbitSign, a free e-signing startup, as a sophomore (runs on AWS)','Finalist in multiple global competitive-programming contests; ranked top 100 in the US on Codeforces','Tutored underserved kids in coding','Self-taught in C++, Python, Kotlin, Java, and several other languages'],
    essay:'Not publicly detailed; his father has instead spoken publicly about the family\'s view that the outcome reflected discrimination in holistic admissions review.',
    story:'A Palo Alto, California student with a 4.42 weighted GPA and a 1590 SAT score, Zhong ran his own startup and had already been recruited by Google as a teenager. Despite this, he was rejected by the large majority of the 18 colleges he applied to. He enrolled at UT Austin before deciding to join Google full-time instead. He and his father later filed federal lawsuits against several public university systems alleging racial discrimination in admissions — claims those universities have not been found liable for in court.',
    sourceName:'CBS News / EdSource / ABC7 San Francisco', sourceUrl:'https://edsource.org/updates/bay-area-teen-rejected-by-16-colleges-files-racial-discrimination-lawsuit'
  },
  {
    id:'limmy', name:'"Limmy" (TikTok creator)', region:'global', tags:['waitlisted','rejected'], year:'2023', country:'United States',
    initials:'L',
    stats:{sat:'1590'},
    accepted:[], waitlisted:['Princeton','Brown'], rejected:['Harvard','Yale','Columbia','Cornell','UPenn','Dartmouth (deferred, then rejected)'],
    highlight:'Valedictorian, 1590 SAT — waitlisted at 2 Ivies, rejected by the rest',
    extracurriculars:['Valedictorian of his high school class'],
    essay:'Not publicly detailed — documented primarily through his own reaction videos rather than a published profile.',
    story:'A high school valedictorian with a 1590 SAT score, Limmy documented his full set of Ivy League results on TikTok: waitlisted at Princeton and Brown, rejected outright by four more, and deferred before being rejected at Dartmouth — a widely shared example of how thin the margin can be even for near-perfect applicants.',
    sourceName:'YourTango', sourceUrl:'https://www.yourtango.com/news/valedictorian-high-sat-score-rejected-every-ivy-league-school'
  },
  {
    id:'chowdhury', name:'Salman Chowdhury', region:'global', tags:['admitted'], year:'2025', country:'United States',
    initials:'SC',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Harvard','Yale','Princeton','Columbia','UPenn','and 5 more (10 of the top 25 he applied to)'],
    waitlisted:[], rejected:[],
    highlight:'Bangladeshi-American from a visa-lottery immigrant family — admitted to 10 of the top 25 US universities',
    extracurriculars:['One of only 16 students statewide to ace New Jersey\'s state learning assessment, and the first in his district to also score perfectly on the language portion that year','Completed the geometry curriculum by 8th grade','Graduated from PCTI STEM Academy in Wayne, New Jersey'],
    essay:'Built his application narrative around the values his immigrant parents instilled in him and how his faith shaped his approach to science and community — themes his teachers echoed in their recommendation letters.',
    story:'Born in Dubai to a family that immigrated to the US from Chattogram, Bangladesh, through the diversity visa lottery, Chowdhury grew up in Paterson, New Jersey. He was accepted to 10 of the top 25 universities in the US, including Harvard, Yale, Princeton, Columbia, and UPenn, and enrolled at Harvard to study Applied Mathematics.',
    sourceName:'CNBC Make It, via NBC affiliates', sourceUrl:'https://www.nbcwashington.com/news/business/money-report/i-got-accepted-to-harvard-stanford-and-princeton-3-things-my-parents-did-at-an-early-age-it-made-all-the-difference/3968707/?amp=1'
  },
  {
    id:'adorsoo', name:'Clinton Edem Adorsoo', region:'global', tags:['admitted'], year:'2026', country:'Ghana',
    initials:'CA',
    stats:{sat:'99th percentile on both sections'},
    accepted:['Harvard (full scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Once sold sachet water to fund his education — now Harvard-bound on a full scholarship',
    extracurriculars:['Contestant for Keta Senior High Technical School in Ghana\'s National Science and Maths Quiz (NSMQ)','Selected as 1 of 25 scholars in the Young Achievers Foundation Ghana program','Prepared with Walden Test Prep and Tutoring Services'],
    essay:'Not publicly detailed in available coverage.',
    story:'Adorsoo grew up in Ashaiman, Ghana, where he once sold sachet water to help fund his education. A contestant in Ghana\'s National Science and Maths Quiz at Keta Senior High Technical School, he scored in the 99th percentile on both SAT sections and was awarded a full scholarship to Harvard.',
    sourceName:'YEN.com.gh', sourceUrl:'https://yen.com.gh/education/306926-clinton-adorsoo-nsmq-star-gains-admission-harvard-university-full-scholarship-photos/'
  },
  {
    id:'oliveira', name:'Sofia Santos de Oliveira', region:'global', tags:['admitted'], year:'2026', country:'Brazil',
    initials:'SO',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Harvard','Yale','Stanford'],
    waitlisted:[], rejected:[],
    highlight:'Low-income Brazilian public-school student — triple-admitted to Harvard, Yale and Stanford',
    extracurriculars:['Selected through Ismart, a Brazilian NGO that places low-income students into scholarships at elite private schools','By her own account, balances an ordinary teenage routine — the gym, friends, social media — alongside her studies'],
    essay:'Not publicly detailed in available coverage, beyond her stated approach of proactively seeking out opportunities rather than waiting for them to appear.',
    story:'Growing up in the Barreiro region of Belo Horizonte, Brazil, Oliveira was selected by Ismart, a nonprofit that places low-income students into scholarships at elite private schools. She was accepted to Harvard, Yale, and Stanford, and chose Harvard to study Chemistry and Social Studies with a full four-year scholarship — worth an estimated R$2 million (roughly $400,000) — covering tuition, housing, and a stipend.',
    sourceName:'Folha Vitória (Brazil)', sourceUrl:'https://www.folhavitoria.com.br/geral/aluna-mineira-de-baixa-renda-vai-a-harvard/'
  },
  {
    id:'goyanna', name:'Ana Beatriz Araujo Santa Cruz Goyanna', region:'global', tags:['admitted'], year:'2026', country:'Brazil',
    initials:'AG',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Harvard (Neuroscience, ~R$2,000,000 / ~$400,000 full scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Brazilian public-school student admitted to Harvard for neuroscience — reaction video went viral',
    extracurriculars:['Public-school student in the Federal District (Brasília), Brazil','Undergraduate researcher at the University of Brasília (UnB) since 2021, as a scholar in Brazil\'s national CNPq scientific-initiation program'],
    essay:'Said she chose neuroscience after noticing how little is understood about mental health among people close to her, and wants to bring that expertise back to Brazil.',
    story:'A public-school student from Brasília, Brazil, Goyanna has done research at the University of Brasília since 2021 as a scholar in the national CNPq scientific-initiation program. She was admitted to Harvard to study neuroscience with a full scholarship valued at roughly R$2 million (about $400,000), planning to bring that expertise back to Brazil. Her reaction video, filmed with her parents, went viral on Brazilian social media.',
    sourceName:'O Liberal (Brazil)', sourceUrl:'https://www.oliberal.com/brasil/estudante-brasileira-de-17-anos-conquista-bolsa-integral-de-r-2-milhoes-em-harvard-1.1064470'
  },
  {
    id:'zhao', name:'Hubert Zhao', region:'global', tags:['rejected'], year:'2021', country:'United States',
    initials:'HZ',
    stats:{gpa:'5.3 weighted'},
    accepted:[], waitlisted:[], rejected:['Cornell','Columbia'],
    highlight:'National Merit Scholar with a 5.3 weighted GPA — rejected by Cornell and Columbia',
    extracurriculars:['President and captain of his high school\'s Science Olympiad, Debate, and Science Bowl teams','National Merit Scholarship recipient'],
    essay:'Not publicly detailed; his family\'s public statements focused on the discrimination complaint they filed rather than his application content.',
    story:'A Chinese-American student from Orlando, Florida, Zhao led three academic teams at his high school and held a 5.3 weighted GPA as a National Merit Scholar. After being rejected by Cornell and Columbia, he and his father — Yukong Zhao, president of the Asian American Coalition for Education — filed a federal civil rights complaint alleging discrimination, joining a broader pattern of similar complaints against Ivy League admissions offices.',
    sourceName:'NextShark, via AsAm News', sourceUrl:'https://nextshark.com/hubert-zhao-ivy-league-complaint'
  },
  {
    id:'jwang', name:'Jon Wang', region:'global', tags:['rejected'], year:'2022', country:'United States',
    initials:'JW',
    stats:{gpa:'4.65',sat:'1590 (perfect Math section)'},
    accepted:['Georgia Institute of Technology'], waitlisted:[], rejected:['MIT','Caltech','Princeton','Harvard','Carnegie Mellon','UC Berkeley'],
    highlight:'Perfect SAT Math score — rejected by MIT, Caltech, Princeton, Harvard, Carnegie Mellon and UC Berkeley',
    extracurriculars:['Achieved a perfect score on the SAT Math section','Son of Chinese immigrant parents'],
    essay:'Not publicly detailed; his public comments instead focused on his belief that race-conscious admissions policies affected his results.',
    story:'A Florida student with a 4.65 GPA and a perfect SAT Math score, Wang was rejected by six elite schools he applied to. He later joined a Supreme Court case seeking to end race-conscious admissions, saying an admissions calculator had shown him a 20% chance of acceptance to Harvard as an Asian-American applicant versus a 95% chance had he been Black. He enrolled at Georgia Tech instead.',
    sourceName:'Yahoo News / Fox News', sourceUrl:'https://news.yahoo.com/asian-american-student-1590-sat-171857237.html'
  },
  {
    id:'guia', name:'Carl Audric Guia', region:'global', tags:['admitted'], year:'2023', country:'Philippines',
    initials:'CG',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Harvard (Astrophysics, full scholarship)','Princeton','Yale','Stanford','Notre Dame (Glynn Family Honors + Stamps Scholars, full ride)'],
    waitlisted:[], rejected:[],
    highlight:'Full scholarships to Harvard, Princeton, Yale and Stanford — from a rural Philippine public high school',
    extracurriculars:['Student at University of the Philippines Rural High School (UPRHS), Laguna province','Pursued an interest in astronomy and astrophysics throughout high school'],
    essay:'Framed his application around his passion for astronomy, which drew him toward Harvard\'s Smithsonian Center for Astrophysics specifically.',
    story:'Carl Audric Guia, a student at the University of the Philippines Rural High School, received full-scholarship offers from Harvard, Princeton, Yale, and Stanford within two days of each other in March 2023, plus the Glynn Family Honors and Stamps Scholars programs at Notre Dame. He chose Harvard to study Astrophysics, drawn by the Harvard-Smithsonian Center for Astrophysics.',
    sourceName:'ABS-CBN News', sourceUrl:'https://abs-cbn.com/life/04/19/23/up-rural-high-school-student-gets-offers-from-5-us-universities'
  },
  {
    id:'collins', name:'Ita Collins', region:'global', tags:['admitted'], year:'2026', country:'South Africa',
    initials:'IC',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case, though she was named to the IEB Outstanding List — see the source for full context.',
    accepted:['Harvard','Stanford','UPenn','Brown','Carnegie Mellon','Harvey Mudd College'],
    waitlisted:[], rejected:[],
    highlight:'Head Girl with nine distinctions — sparked an Ivy League bidding war for her talents',
    extracurriculars:['2025 Head Girl of Roedean School (Johannesburg, South Africa)','Graduated with nine distinctions and was named to the IEB (Independent Examinations Board) Outstanding List','Served on the Student Representative Council','Active in environmental activism and multiple school sports','Completed an internship at the Wits Reproductive Health Institute','Worked with Crimson Education mentors on her application strategy'],
    essay:'Her application deliberately favored narrative depth over a checklist of achievements — she and her advisors focused on which of her existing activities (environmental work, the Wits internship, her SRC role) carried the most weight, rather than padding her resume with extra activities.',
    story:'Ita Collins, the 2025 Head Girl of Roedean School in South Africa, graduated with nine distinctions and a spot on the IEB Outstanding List, and received offers from Harvard, Stanford, UPenn, Brown, Carnegie Mellon, and Harvey Mudd College. She will study Environmental Studies at Harvard, combining science and policy with a public health focus drawn from her internship experience.',
    sourceName:'IOL / Weekend Argus (South Africa)', sourceUrl:'https://iol.co.za/weekend-argus/2026-06-18-how-a-south-african-matriculant-secured-admission-to-harvard-university/'
  },
  {
    id:'ncube', name:'Gertrude Ncube', region:'global', tags:['admitted'], year:'2022', country:'Zimbabwe',
    initials:'GN',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Harvard (via the US Embassy\'s United States Achievers Program)'],
    waitlisted:[], rejected:[],
    highlight:'Distinctions in Math, Physics and Chemistry from Bulawayo, Zimbabwe — plans to return home to work on science solutions',
    extracurriculars:['Graduate of USAP Community School and St Columbus High School, Bulawayo','Scholar in the US Embassy\'s United States Achievers Program (USAP)'],
    essay:'Not publicly detailed in available coverage.',
    story:'Born and raised in Pumula East, Bulawayo, Ncube earned distinctions in Mathematics, Physics, and Chemistry and was accepted to Harvard through the US Embassy\'s United States Achievers Program. Under the terms of her scholarship, she plans to return to Zimbabwe after graduating to work on science-based solutions to problems facing her community.',
    sourceName:'Amakhosikazi Media (Zimbabwe)', sourceUrl:'https://amakhosikazimedia.org/2023/02/10/harvard-university-acceptance-for-bulawayo-female-student/'
  },
  {
    id:'mukhammadieva', name:'Feruza Mukhammadieva', region:'uz', tags:['admitted'], year:'2022', country:'Uzbekistan',
    initials:'FMu',
    stats:{}, statsNote:'Specific GPA/SAT/IELTS scores were not published for this case — see the source for full context.',
    accepted:['Princeton','New York University Abu Dhabi (NYUAD)','Georgetown','Carnegie Mellon (all four with full-ride scholarships)'],
    waitlisted:[], rejected:[],
    highlight:'Full rides to 4 schools at once — Princeton, NYU Abu Dhabi, Georgetown and Carnegie Mellon',
    extracurriculars:['Alumna of school No. 32 in Kokand','Career development chairperson, Society of Women Engineers at Princeton','Speaker outreach for Princeton\'s Entrepreneurship Club','Co-founder of the Princeton Central Asian Student Association'],
    essay:'Not publicly detailed in available coverage.',
    story:'Mukhammadieva, an alumna of school No. 32 in Kokand, was admitted with full-ride scholarships to Princeton, NYU Abu Dhabi, Georgetown, and Carnegie Mellon in the same Class of 2026 wave of Uzbekistan acceptances that included several of her peers. She chose Princeton, where she pursues Computer Science with a minor in Machine Learning, and helped lead the campus\'s Society of Women Engineers chapter and Entrepreneurship Club, and co-founded the Princeton Central Asian Student Association.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'murodiy', name:'Farangiz Murodiy', region:'uz', tags:['admitted'], year:'2023', country:'Uzbekistan',
    initials:'FMd',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Stanford (full-ride: tuition, food, housing, and flights)'],
    waitlisted:[], rejected:[],
    highlight:'Full ride to Stanford to study Symbolic Systems with a Human-Centered AI concentration',
    extracurriculars:['One of the founding members of the Central Asian Student Association at Stanford','Interviewed fellow Uzbek admit Abdulaziz Sobirov about his own college admissions journey for Gazeta.uz'],
    essay:'Not publicly detailed in available coverage.',
    story:'Farangiz Murodiy was accepted to Stanford University with a scholarship covering tuition, food, housing, and flights to the US. Now a sophomore majoring in Symbolic Systems with a concentration in Human-Centered Artificial Intelligence, she has since helped pioneer a Central Asian Student Association on campus.',
    sourceName:'Gazeta.uz', sourceUrl:'https://gazeta.uz/en/2024/06/23/us-universities'
  },
  {
    id:'fayzullaeva', name:'Allomakhon Fayzullaeva', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'AF',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Brown ($376,000 scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Self-taught SAT prep from a school with no IB/AP/A-level program — admitted to Brown with a $376,000 scholarship',
    extracurriculars:['Graduated from the Academic Lyceum under the University of World Economy and Diplomacy (concentration: exact sciences and German language)','Won the PASCH-Youth Courses scholarship from the Goethe-Institut for a summer language program in Bavaria, Germany (2022)','Awarded a dean\'s scholarship for academic achievement at her lyceum','Attended public school No. 178 in Tashkent through 9th grade','Took online courses on Coursera and worked as a private IELTS tutor during her gap year to keep growing academically without access to IB/AP/A-levels'],
    essay:'Not publicly detailed, beyond her account of spending the summer after graduation independently improving her SAT score, researching colleges, and revising her application essays, since her school offered no IB, AP, or A-level curriculum to lean on.',
    story:'Fayzullaeva attended a public school in Tashkent through ninth grade before transferring to a specialized lyceum focused on exact sciences and German. Without access to an internationally recognized curriculum, she spent the summer after graduation independently preparing her SAT scores and application essays. She was admitted to Brown University to study Political Science and Gender Studies with a scholarship worth $376,000, and hopes to use that background to improve female political participation in Uzbekistan.',
    sourceName:'Gazeta.uz', sourceUrl:'https://gazeta.uz/en/2024/06/23/us-universities'
  },
  {
    id:'qironov', name:'Husniddin Qironov', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'HQ',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['New York University (main campus, Global Liberal Studies)'],
    waitlisted:[], rejected:[],
    highlight:'Admitted to NYU\'s Global Liberal Studies program in the same Uzbekistan admissions wave',
    extracurriculars:['Alumnus of Target International School, a private school in Tashkent, following Uzbekistan\'s national curriculum'],
    essay:'Not publicly detailed in available coverage.',
    story:'Husniddin Qironov, an alumnus of Target International School in Tashkent, was admitted to the main campus of New York University\'s Liberal Studies school, where he intends to major in the Global Liberal Studies program.',
    sourceName:'Gazeta.uz', sourceUrl:'https://gazeta.uz/en/2024/06/23/us-universities'
  },
  {
    id:'abdrshin', name:'Asad Abdrshin', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'AAb',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Vanderbilt ($384,000 scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'From Tashkent to a Norwegian boarding school to Vanderbilt, on a $384,000 scholarship',
    extracurriculars:['Alumnus of United World College Red Cross Nordic (UWC RCN), an international high school in Norway','Completed the IB Diploma Programme'],
    essay:'Described the selection to attend UWC in Norway as the pivotal moment of his education, saying it transformed him academically, spiritually, and culturally.',
    story:'Originally from Tashkent, Abdrshin was selected to attend United World College Red Cross Nordic in Norway, where he completed the IB Diploma Programme. He was admitted to Vanderbilt University with a $384,000 scholarship to study Mathematics.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'saidov', name:'Sayfullo Saidov', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'SS',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Princeton ($357,000 scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Princeton, $357,000 scholarship — originally from Bukhara, raised partly in Japan',
    extracurriculars:['High school senior at Presidential School (PS) in Tashkent','Guided through the admissions process by Freshman Academy, a college admissions consultancy'],
    essay:'Not publicly detailed in available coverage.',
    story:'Originally from Bukhara, Saidov spent a considerable part of his childhood living in Japan with his family before returning to attend Presidential School in Tashkent. He was accepted to Princeton with a $357,000 scholarship and intends to study Chemical and Biological Engineering.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'abdusamatov', name:'Salim Abdusamatov', region:'uz', tags:['admitted'], year:'2024', country:'Uzbekistan',
    initials:'SA',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['New York University, Tandon School of Engineering'],
    waitlisted:[], rejected:[],
    highlight:'Admitted to NYU Tandon for Civil Engineering, following the A-Level curriculum in Tashkent',
    extracurriculars:['High school senior at Cambridge International College in Tashkent, following the A-Level curriculum','Guided through the admissions process by Freshman Academy'],
    essay:'Not publicly detailed in available coverage.',
    story:'Salim Abdusamatov, a senior at Cambridge International College in Tashkent following the A-Level curriculum, was admitted to the main campus of NYU\'s Tandon School of Engineering, where he intends to study Civil Engineering.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'sodikova', name:'Gulrukh Sodikova', region:'uz', tags:['admitted'], year:'2023', country:'Uzbekistan',
    initials:'GS',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['University of Pennsylvania (full-ride scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Full ride to UPenn for Philosophy, Politics and Economics — with an eye on law school',
    extracurriculars:['Alumna of Presidential School (PS) in Tashkent','Member of the "Et Cetera" team at the Zakovat Students League quiz bowl, alongside fellow admit Abdulaziz Sobirov'],
    essay:'Not publicly detailed in available coverage.',
    story:'A Presidential School Tashkent alumna, Sodikova was admitted to the University of Pennsylvania with a full-ride scholarship. She is pursuing Philosophy, Politics and Economics (PPE) in the College of Arts and Sciences, with plans to continue on to law school.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'abdukholikov', name:'Khosilmurod Abdukholikov', region:'uz', tags:['admitted'], year:'2023', country:'Uzbekistan',
    initials:'KA',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Yale (full-ride scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'From a rural public school in Jizzakh region to Yale, on a full ride',
    extracurriculars:['Alumnus of public high school No. 60 in Bakhmal district, Jizzakh region','Guided through the admissions process by Freshman Academy'],
    essay:'Framed his goals around expanding educational opportunities for young people from villages with limited resources, drawing on his own background in rural Jizzakh region.',
    story:'Coming from Bakhmal district in Jizzakh region and a public high school with limited resources, Abdukholikov was admitted to Yale University with a full-ride scholarship. He studies Computer Science and Philosophy while also learning German, and has said he hopes to use his Yale education to help expand educational access for students from villages like his own.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'assatilloyeva', name:'Parizoda Assatilloyeva', region:'uz', tags:['admitted'], year:'2023', country:'Uzbekistan',
    initials:'PA',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Columbia (John Jay Scholars Program)'],
    waitlisted:[], rejected:[],
    highlight:'Public-school student from Samarkand — Columbia\'s John Jay Scholars Program',
    extracurriculars:['Alumna of a public school in Samarkand','Guided through the admissions process by Freshman Academy'],
    essay:'Not publicly detailed in available coverage.',
    story:'Assatilloyeva, an alumna of a public school in Samarkand, was admitted to Columbia University as part of its John Jay Scholars Program. She now studies Political Science as a student in the College of Arts and Sciences.',
    sourceName:'Gazeta.uz', sourceUrl:'https://www.gazeta.uz/en/2024/06/23/us-universities/'
  },
  {
    id:'beksultanov', name:'Amirtai Beksultanov', region:'global', tags:['admitted'], year:'2026', country:'Kyrgyzstan',
    initials:'AB',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Stanford (full scholarship)'],
    waitlisted:[], rejected:[],
    highlight:'Kyrgyzstan\'s full-scholarship Stanford admit — met by the country\'s Cabinet Chairman',
    extracurriculars:[],
    essay:'Not publicly detailed in available coverage.',
    story:'Beksultanov, from Kyrgyzstan, was admitted to Stanford University with a full scholarship to pursue his bachelor\'s degree. His achievement was publicly recognized by Kyrgyzstan\'s Cabinet of Ministers, whose chairman met with him to congratulate him on his preparation and determination.',
    sourceName:'24.kg (Kyrgyzstan)', sourceUrl:'https://24.kg/english/369342__Kyrgyzstani_admitted_to_Stanford_on_full_scholarship_'
  },
  {
    id:'laeno', name:'Nicole Laeno', region:'global', country:'United States', tags:['rejected'], year:'2024',
    initials:'NL',
    stats:{}, statsNote:'Specific GPA/SAT scores were not published for this case — see the source for full context.',
    accepted:['Cal State Long Beach','UC Santa Cruz','UC Riverside','Cal Poly San Luis Obispo','San Diego State'],
    waitlisted:[], rejected:['UCLA'],
    highlight:'47 million views — rejected from her lifelong dream school, UCLA',
    extracurriculars:['Content creator and dancer since middle school, with millions of followers across TikTok and YouTube','Regularly visited UCLA\'s campus and attended its dance-team clinics throughout high school while preparing to apply'],
    essay:'Not publicly detailed in available coverage.',
    story:'A Torrance, California high school senior and longtime social media creator, Laeno had dreamed of attending UCLA since middle school, visiting its campus and dance clinics throughout high school. On April 2, 2024, she was accepted to Cal State Long Beach, UC Santa Cruz, UC Riverside, Cal Poly San Luis Obispo, and San Diego State, but rejected from UCLA. Her filmed reaction went viral, reaching over 47 million views, and she has since spoken publicly about her decision to share the rejection alongside the acceptances rather than hide it.',
    sourceName:'ABC News / Good Morning America', sourceUrl:'https://abcnews.go.com/living/story/18-year-wanted-share-rejection-dream-school-109165726'
  },
  {
    id:'tuksanov', name:'Parviz Tuksanov', region:'uz', country:'Uzbekistan', tags:['admitted'], year:'2025',
    initials:'PT',
    stats:{sat:'1600 (Dec 2024) — first perfect score in Uzbekistan; earlier 1560',ielts:'8.5 (Aug 2022, age 16)'},
    accepted:['NYU Abu Dhabi (Class of 2029)'],
    waitlisted:[], rejected:[],
    highlight:'Uzbekistan\'s first perfect 1600 SAT — self-taught from a regular public school in Bukhara, now at NYU Abu Dhabi',
    academics:[
      'Attended general secondary School No. 2 in Bukhara — not a specialized, private or international school',
      'Started learning English in 4th grade; scored IELTS 8.5 at age 16 (August 2022)',
      'Began SAT prep on his own with Khan Academy, YouTube lessons, podcasts and books, because no SAT courses or tutors existed in Bukhara at the time',
      'His practice scores reportedly stalled around 1350 for more than three months before he joined Freshman Academy\'s Digital SAT program in April 2023',
      'June 2023 SAT: 1560 (790 Math / 770 Reading & Writing)',
      'December 2024 SAT, retaken alongside his own students: 1600 — the first perfect score ever recorded by an Uzbekistani',
      'His view on why 1600 is rare: with only 98 questions, a single mistake rules it out, and most test-takers stop retaking once they pass 1500',
      'Reviewed 25+ past SAT tests with his students before the final attempt to fix his time management',
      'Research: winner of the "CIS Leaders" competition, and was working on a paper on factors affecting consumer behavior in post-Soviet Central Asia',
      'Stated academic interests before applying: economics and psychology; at NYU Abu Dhabi his public bio lists Economics/Finance and Politics'
    ],
    background:[
      'From Bukhara, Uzbekistan; 18 years old when he set the SAT record',
      'His mother publicly urged Uzbek parents to invest in their children\'s education rather than lavish wedding spending, citing her son as the example',
      'On February 14, 2025, President Shavkat Mirziyoyev congratulated him at a meeting with young people and thanked his parents and coaches',
      'The size of his NYU Abu Dhabi financial aid package has not been published'
    ],
    extracurriculars:[
      'Taught SAT classes at Ad Astra School in Bukhara (established September 2022), which he has been described as founding; small groups, weekly mock tests, admission by math test plus interview',
      'Worked for two years as an SAT mentor to peers, which he credits with sharpening his own skills',
      'Featured in Ad Astra School\'s podcast series (Ep. 3 in January 2024 and Ep. 45 in December 2024)',
      'At NYU Abu Dhabi: peer tutor in the social sciences and SAT instructor while carrying a heavy course load and searching for internships',
      'Runs a Telegram channel (3,000+ subscribers) on SAT strategy, college life, reading and AI policy'
    ],
    essay:'His application essay was not published. What is public: before applying he described his interests as economics and psychology, and was researching consumer behavior in post-Soviet Central Asia.',
    story:'Parviz Tuksanov (also spelled Tuksonov or To\'qsonov) grew up in Bukhara and studied at a regular public school, where he began learning English in fourth grade. He earned an IELTS 8.5 at 16, taught himself the SAT from free online resources, scored 1560 in 2023, and then taught SAT classes to peers. In December 2024 he retook the exam alongside his own students and scored 1600, the first perfect result in Uzbekistan\'s history. The President of Uzbekistan congratulated him publicly two months later. He enrolled at NYU Abu Dhabi in the Class of 2029, according to his own public Telegram channel and LinkedIn profile; NYUAD\'s financial aid amount for him has not been published.',
    sourceName:'Kun.uz (interview), Ta\'lim xabarlari, Freshman Academy', sourceUrl:'https://kun.uz/en/news/2025/01/14/uzbekistans-first-perfect-sat-scorer-shares-his-journey'
  }
];
